### ISSUE TITLE
How to reproduce Figure 8 result

### ISSUE THREAD

**Issue by sonnguyenasu** [eniac/flamingo#1]
Hi,
Thank you for publishing the code and for an amazing work on the secure aggregation paper.
I would like to ask the way to reproduce the result on Figure 8, comparing BBGLR and Flamingo completion time.
Thank you.

**Comment by Yiping106283** [comment]
Hi, thanks for your interest in this work!

You can run: 
`python abides.py -c flamingo -n 1024 -i 10 -p 1`
`python abides.py -c google_malicious -n 1024 -i 10 -p 1`

The completion time and the summation result (for unary vectors) for each iteration will be printed out. For the latter, you need to divide by the number of clients (1024 in this case) to get the summation accuracy. 

Note: the simulator takes some time to set up for 1024 clients. If there is no output after a while, try running the program on a machine with larger memory.   

Please let me know if you have more questions!

**Comment by Salterwater23** [comment]
Hi,
Thank you for publishing the code and for an amazing work on the secure aggregation paper.
I am a newbie who just got started with security aggregation.
I would like to ask if there is any visualization generated in this project...

**Comment by Yiping106283** [comment]
Hi, thanks for your interest! We have numbers printed out in each round of training, but unfortunately we don't have visualization.

**Comment by Salterwater23** [comment]
Thank you very much. I am very honored to receive your reply.

**Comment by Salterwater23** [comment]
One more question, is committee equivalent to Decryptors in your code?

**Comment by Yiping106283** [comment]
Yes, that's right.
